"""The `biology` pack, version 1: 345 categories, adopted by merge.

GENERATED — do not edit by hand. Built by consensus in the sister repo
github.com/petfold/ontodag-core (packs/biology, commit b58fdab) from WordNet 3.0
and Wikidata with hand rulings; every name is a plain word that no everyday
sense already owns (a pack never takes an everyday word). It presumes `core`,
which `pack biology` applies first; core's names appear below only as parents.
`BORROWED` are names that belong to a sibling pack — entered parentless so
this pack adopts on its own, filed the moment the sibling is adopted
(refinement by merge). ontodag-core's docs/UPPER.md §8 is the record.
"""

VERSION = 1

BORROWED = ()

# (name, parents) — sorted by name.
PACK = (
    ('acanthocyte', ('cell',)),
    ('acid-base-equilibrium', ('state',)),
    ('akaryocyte', ('cell',)),
    ('allele', ('gene',)),
    ('ameloblast', ('embryonic-cell',)),
    ('amphidiploid', ('organism',)),
    ('animal-egg', ('ovum',)),
    ('anisogamete', ('gamete',)),
    ('anisogamy', ('reproduction',)),
    ('annual-plant', ('plant',)),
    ('antagonistic-muscle', ('muscle',)),
    ('antherozoid', ('gamete',)),
    ('apogamy', ('reproduction',)),
    ('apophysis', ('body-part',)),
    ('appositional-growth', ('growth', 'organic-process')),
    ('archespore', ('cell',)),
    ('arthrospore', ('cell',)),
    ('astrocyte', ('neurogliacyte',)),
    ('autoregulation', ('organic-process',)),
    ('axon', ('nerve-fiber',)),
    ('b-cell', ('lymphocyte',)),
    ('bacterial-transformation', ('event',)),
    ('basophil', ('granulocyte',)),
    ('beta-cell', ('cell',)),
    ('biennial-plant', ('plant',)),
    ('biological-accretion', ('increase',)),
    ('biological-activator', ('substance',)),
    ('biological-association', ('group',)),
    ('biological-decomposition', ('process',)),
    ('biological-dimorphism', ('morphological-polymorphism',)),
    ('biological-inhibition', ('organic-process',)),
    ('biological-isomorphism', ('attribute',)),
    ('biological-polymorphism', ('organic-phenomenon',)),
    ('biological-specialization', ('organic-process',)),
    ('biological-valence', ('attribute',)),
    ('biologist', ('scientist',)),
    ('biotic-community', ('group',)),
    ('blastema', ('tissue',)),
    ('blastocyte', ('embryonic-cell',)),
    ('blastomere', ('embryonic-cell',)),
    ('blood-cell', ('somatic-cell',)),
    ('bodily-humour', ('substance',)),
    ('bone-cell', ('somatic-cell',)),
    ('botanical-cohesion', ('growth', 'organic-process')),
    ('botanical-division', ('phylum',)),
    ('brachium', ('body-part',)),
    ('bract-tuft', ('bunch',)),
    ('brain-cell', ('nerve-cell',)),
    ('calyx', ('plant-part',)),
    ('cancer-cell', ('neoplastic-cell',)),
    ('cataplasia', ('change',)),
    ('cell-theory', ('concept',)),
    ('choanocyte', ('flagellated-cell',)),
    ('chromosomal-inversion', ('mutation',)),
    ('chromosomal-translocation', ('organic-process',)),
    ('chromosome', ('natural-object',)),
    ('cloning-vector', ('physical-object',)),
    ('coarctation', ('attribute', 'event')),
    ('columnar-cell', ('epithelial-cell',)),
    ('cone-cell', ('visual-cell',)),
    ('corolla', ('plant-part',)),
    ('cosmid', ('cloning-vector', 'virus')),
    ('crustacean-roe', ('spawn',)),
    ('cuboidal-cell', ('epithelial-cell',)),
    ('culture-medium', ('substance',)),
    ('cybernetics', ('science',)),
    ('cystic-fibrosis-transport-regulator', ('mutant-gene',)),
    ('daughter-cell', ('cell',)),
    ('dehiscence', ('organic-phenomenon',)),
    ('dendrite', ('nerve-fiber',)),
    ('diploid', ('organism',)),
    ('dissilience', ('event',)),
    ('dna', ('nucleic-acid',)),
    ('dna-replication', ('organic-process',)),
    ('dominant-allele', ('allele',)),
    ('dominant-gene', ('gene',)),
    ('ecological-establishment', ('process',)),
    ('ecological-niche', ('condition',)),
    ('ecological-succession', ('organic-process',)),
    ('ecosystem', ('environment',)),
    ('effector', ('nerve-fiber',)),
    ('embryonic-cell', ('cell',)),
    ('enzyme', ('biological-activator', 'protein')),
    ('eosinophil', ('granulocyte',)),
    ('epidermal-cell', ('skin-cell',)),
    ('epithelial-cell', ('somatic-cell',)),
    ('erythroblast', ('somatic-cell',)),
    ('estivation', ('attribute',)),
    ('etiolation', ('act', 'organic-process')),
    ('fat-cell', ('somatic-cell',)),
    ('fiber-cell', ('cell',)),
    ('fibroblast', ('somatic-cell',)),
    ('fibrous-astrocyte', ('astrocyte',)),
    ('fish-roe', ('animal-egg',)),
    ('fixed-phagocyte', ('phagocyte',)),
    ('flagellated-cell', ('cell',)),
    ('flower-corona', ('natural-object', 'plant-part')),
    ('flower-lip', ('natural-object', 'plant-part')),
    ('flower-spike', ('natural-object', 'plant-part')),
    ('flower-style', ('natural-object', 'plant-part')),
    ('foliation', ('growth', 'organic-process')),
    ('food-chain', ('organic-phenomenon',)),
    ('food-pyramid', ('organic-phenomenon',)),
    ('food-web', ('organic-phenomenon',)),
    ('form-family', ('taxonomic-family',)),
    ('form-genus', ('genus',)),
    ('free-phagocyte', ('phagocyte',)),
    ('gamete', ('reproductive-cell',)),
    ('gametocyte', ('cell',)),
    ('ganglion-cell', ('nerve-cell',)),
    ('gene', ('physical-object',)),
    ('gene-deletion', ('mutation',)),
    ('gene-expression', ('organic-process',)),
    ('gene-mapping', ('procedure',)),
    ('gene-transcription', ('chemical-reaction', 'organic-process')),
    ('genetic-carrier', ('organism',)),
    ('genetic-dominance', ('organic-phenomenon',)),
    ('genetic-inheritance', ('attribute',)),
    ('genetic-linkage', ('genetic-inheritance',)),
    ('genetic-marker', ('gene',)),
    ('genetic-recombination', ('organic-process',)),
    ('genetic-reversion', ('mutation',)),
    ('genetic-segregation', ('organic-process',)),
    ('genetic-transduction', ('organic-process',)),
    ('genetic-transposition', ('mutation',)),
    ('genus', ('taxonomic-group',)),
    ('genus-pan', ('genus',)),
    ('germ-tube', ('natural-object', 'plant-part')),
    ('goblet-cell', ('epithelial-cell',)),
    ("golgi's-cell", ('brain-cell',)),
    ('granulocyte', ('leukocyte',)),
    ('hair-cell', ('epithelial-cell',)),
    ('haploid', ('organism',)),
    ('haplotype', ('combination',)),
    ('helper-t-cell', ('t-cell',)),
    ('hematopoeitic-stem-cell', ('stem-cell',)),
    ('heritable-character', ('attribute',)),
    ('heterology', ('attribute',)),
    ('heteroploid', ('organism',)),
    ('heterosis', ('attribute',)),
    ('heterozygote', ('organism',)),
    ('histiocyte', ('macrophage',)),
    ('homeobox', ('homeotic-gene',)),
    ('homeostasis', ('equilibrium',)),
    ('homeotic-gene', ('gene',)),
    ('homogeny', ('similarity',)),
    ('homozygote', ('organism',)),
    ('hormone', ('secretion',)),
    ('hybridization', ('organic-process',)),
    ('hybridoma', ('somatic-cell',)),
    ('immune-recognition', ('organic-phenomenon',)),
    ('insertional-mutagenesis', ('event',)),
    ('intussusception', ('growth', 'organic-process')),
    ('isogamete', ('gamete',)),
    ('isogamy', ('reproduction',)),
    ('killer-t-cell', ('t-cell',)),
    ("kupffer's-cell", ('cell',)),
    ('leaf-lobe', ('natural-object', 'plant-part')),
    ('leaf-node', ('body-part',)),
    ('lethal-gene', ('gene',)),
    ('leukocyte', ('blood-cell',)),
    ('leydig-cell', ('cell',)),
    ('ligule', ('natural-object', 'plant-part')),
    ('limb-abduction', ('motion',)),
    ('limb-adduction', ('motion',)),
    ('linkage-group', ('collection',)),
    ('localization-of-function', ('scientific-principle',)),
    ('lymphoblast', ('lymphocyte',)),
    ('lymphocyte', ('leukocyte',)),
    ('macrophage', ('leukocyte', 'phagocyte')),
    ('mast-cell', ('somatic-cell',)),
    ('medullated-nerve-fiber', ('nerve-fiber',)),
    ('megakaryocyte', ('somatic-cell',)),
    ('megaloblast', ('red-blood-cell',)),
    ('megalocyte', ('red-blood-cell',)),
    ('meiosis', ('organic-process',)),
    ('melanoblast', ('epidermal-cell',)),
    ('melanocyte', ('epidermal-cell',)),
    ('meme', ('cognition', 'information')),
    ("mendel's-law", ('concept',)),
    ('metabolism', ('organic-process',)),
    ('microcyte', ('red-blood-cell',)),
    ('microgliacyte', ('neurogliacyte',)),
    ('microphage', ('neutrophil',)),
    ('modifier-gene', ('gene',)),
    ('monad-organism', ('microorganism',)),
    ('monoblast', ('monocyte',)),
    ('monocyte', ('leukocyte',)),
    ('monotype', ('taxonomic-group',)),
    ('morphological-polymorphism', ('organic-phenomenon',)),
    ('mother-cell', ('cell',)),
    ('motor-fiber', ('material', 'nerve-fiber')),
    ('motor-neuron', ('nerve-cell',)),
    ('muscle-cell', ('fiber-cell', 'somatic-cell')),
    ('muscle-relaxation', ('increase',)),
    ('mutant', ('organism',)),
    ('mutant-gene', ('gene',)),
    ('myeloblast', ('leukocyte',)),
    ('myelocyte', ('leukocyte',)),
    ('naturalist', ('biologist',)),
    ('necrobiosis', ('organic-phenomenon',)),
    ('neoplastic-cell', ('somatic-cell',)),
    ('nerve-cell', ('somatic-cell',)),
    ('nerve-fiber', ('fiber-cell',)),
    ('neural-irradiation', ('event',)),
    ('neural-summation', ('organic-process',)),
    ('neuroblast', ('embryonic-cell',)),
    ('neurogliacyte', ('somatic-cell',)),
    ('neutrophil', ('granulocyte',)),
    ('nit', ('animal-egg',)),
    ('nonallele', ('gene',)),
    ('nucleic-acid', ('compound',)),
    ('nutrition', ('organic-process',)),
    ('oligodendrocyte', ('neurogliacyte',)),
    ('oncogene', ('gene',)),
    ('oocyte', ('gametocyte',)),
    ('oosphere', ('gamete',)),
    ('ootid', ('ovum',)),
    ('operator-gene', ('gene',)),
    ('organic-phenomenon', ('natural-event',)),
    ('organic-process', ('process',)),
    ('osmosis', ('process',)),
    ('osteoblast', ('embryonic-cell',)),
    ('osteoclast', ('bone-cell', 'macrophage')),
    ('osteocyte', ('bone-cell',)),
    ('ovule', ('ovum',)),
    ('ovum', ('gamete',)),
    ('packed-cells', ('cell', 'material')),
    ('papilla', ('body-part',)),
    ('parthenocarpy', ('reproduction',)),
    ('parthenote', ('cell',)),
    ('perennial-plant', ('plant',)),
    ('peristome', ('body-part',)),
    ('phagocyte', ('somatic-cell',)),
    ('phellem', ('bark',)),
    ('phloem', ('natural-object', 'plant-part')),
    ('phylogenetic-relation', ('attribute',)),
    ('phylum', ('taxonomic-group',)),
    ('physiological-control', ('organic-process',)),
    ('physiological-stimulation', ('process',)),
    ('phytohormone', ('material',)),
    ('pitcher-leaf', ('leaf',)),
    ('plant-blister', ('body-part',)),
    ('plant-callus', ('body-part',)),
    ('plant-cell', ('cell',)),
    ('plant-embryo', ('plant',)),
    ('plant-part', ('body-part',)),
    ('plantae', ('taxonomic-group',)),
    ('plasma-cell', ('b-cell',)),
    ('plasmablast', ('plasma-cell',)),
    ('pleomorphism', ('organic-phenomenon',)),
    ('point-mutation', ('mutation', 'organic-process')),
    ('polar-body', ('cell',)),
    ('pollen-tube', ('natural-object', 'plant-part')),
    ('polygene', ('gene',)),
    ('polyploid', ('organism',)),
    ('position-effect', ('natural-event',)),
    ('prickle-cell', ('skin-cell',)),
    ('proto-oncogene', ('gene',)),
    ('protoplasmic-astrocyte', ('astrocyte',)),
    ('purkinje-cell', ('brain-cell',)),
    ('recessive-allele', ('allele',)),
    ('recessive-gene', ('gene',)),
    ('recombinant', ('cell', 'organism')),
    ('red-blood-cell', ('blood-cell',)),
    ('regeneration', ('organic-process',)),
    ('regulatory-gene', ('gene',)),
    ('repressor-gene', ('gene',)),
    ('reproduction', ('organic-process',)),
    ('reproductive-cell', ('cell',)),
    ('reticulocyte', ('red-blood-cell',)),
    ('rna-translation', ('organic-process',)),
    ('rod-cell', ('visual-cell',)),
    ('roe', ('animal-egg',)),
    ('saltation', ('mutation',)),
    ('schwann-cell', ('neurogliacyte',)),
    ('scurf', ('plant-part',)),
    ('sensitiveness', ('sense',)),
    ('sensory-adaptation', ('event',)),
    ('sensory-fiber', ('material', 'nerve-fiber')),
    ('sensory-neuron', ('nerve-cell',)),
    ('sertoli-cell', ('cell',)),
    ('sex-chromosome', ('chromosome',)),
    ('sickle-cell', ('red-blood-cell',)),
    ('sideroblast', ('erythroblast',)),
    ('siderocyte', ('red-blood-cell',)),
    ('silkworm-seed', ('animal-egg',)),
    ('single-nucleotide-polymorphism', ('biological-polymorphism',)),
    ('skin-cell', ('somatic-cell',)),
    ('smooth-muscle-cell', ('muscle-cell',)),
    ('somatic-cell', ('cell',)),
    ('spawn', ('animal-egg',)),
    ('sperm', ('gamete',)),
    ('spermatid', ('gamete',)),
    ('spermatocyte', ('gametocyte',)),
    ('spherocyte', ('red-blood-cell',)),
    ('spindle-fiber', ('natural-object',)),
    ('spongioblast', ('columnar-cell',)),
    ('spore-mother-cell', ('mother-cell',)),
    ('squamous-cell', ('epithelial-cell',)),
    ('stem-cell', ('somatic-cell',)),
    ('striated-muscle-cell', ('muscle-cell',)),
    ('structural-gene', ('gene',)),
    ('subclass', ('taxonomic-group',)),
    ('subfamily', ('taxonomic-group',)),
    ('subgenus', ('taxonomic-group',)),
    ('subkingdom', ('taxonomic-group',)),
    ('suborder', ('taxonomic-group',)),
    ('subphylum', ('taxonomic-group',)),
    ('subspecies', ('taxonomic-group',)),
    ('superclass', ('taxonomic-group',)),
    ('superfamily', ('taxonomic-group',)),
    ('superorder', ('taxonomic-group',)),
    ('superphylum', ('taxonomic-group',)),
    ('suppressor-gene', ('gene',)),
    ('t-cell', ('lymphocyte',)),
    ('taproot', ('plant-root',)),
    ('target-cell', ('somatic-cell',)),
    ('taste-cell', ('epithelial-cell',)),
    ('taxonomic-class', ('taxonomic-group',)),
    ('taxonomic-division', ('taxonomic-group',)),
    ('taxonomic-family', ('taxonomic-group',)),
    ('taxonomic-group', ('concept',)),
    ('taxonomic-order', ('taxonomic-group',)),
    ('taxonomic-tribe', ('taxonomic-group',)),
    ('taxonomic-variety', ('taxonomic-group',)),
    ('taxonomy', ('science',)),
    ('theory-of-evolution', ('concept',)),
    ('theory-of-inheritance', ('concept',)),
    ('transgene', ('gene',)),
    ('tumor-suppressor-gene', ('suppressor-gene',)),
    ('turgor', ('state',)),
    ('type-genus', ('genus',)),
    ('type-species', ('species',)),
    ('type-taxon', ('taxonomic-group',)),
    ('uncus', ('body-part', 'shape')),
    ('unit-character', ('heritable-character',)),
    ('variant', ('taxonomic-group',)),
    ('venation', ('attribute',)),
    ('vernation', ('attribute',)),
    ('visual-accommodation', ('organic-process',)),
    ('visual-cell', ('somatic-cell',)),
    ('x-linked-gene', ('gene',)),
    ('y-linked-gene', ('gene',)),
    ('zygote', ('cell',)),
)
