"""The `chemistry` pack, version 1: 248 categories, adopted by merge.

GENERATED — do not edit by hand. Built by consensus in the sister repo
github.com/petfold/ontodag-core (packs/chemistry, commit fb54269) from WordNet 3.0
and Wikidata with hand rulings; every name is a plain word that no everyday
sense already owns (a pack never takes an everyday word). It presumes `core`,
which `pack chemistry` applies first; core's names appear below only as parents.
`BORROWED` are names that belong to a sibling pack — entered parentless so
this pack adopts on its own, filed the moment the sibling is adopted
(refinement by merge). ontodag-core's docs/UPPER.md §8 is the record.
"""

VERSION = 1

BORROWED = ()

# (name, parents) — sorted by name.
PACK = (
    ('24-karat-gold', ('gold',)),
    ('acid-value', ('attribute',)),
    ('actinide-series', ('chemical-group', 'collection')),
    ('actinium', ('chemical-element', 'radioactive-material')),
    ('activated-carbon', ('carbon',)),
    ('alkali-metal', ('metal',)),
    ('alkaline-earth', ('metal',)),
    ('allomerism', ('variation',)),
    ('allotrope', ('chemical-element',)),
    ('alloy', ('mixture',)),
    ('alloy-iron', ('cast-iron',)),
    ('alpha-iron', ('iron',)),
    ('alum', ('chemical-element', 'compound')),
    ('americium', ('metal', 'radioactive-material')),
    ('ammonia-alum', ('chemical-element', 'compound')),
    ('amount-of-substance', ('linear-dimension',)),
    ('anticatalyst', ('substance',)),
    ('antimonial-lead', ('lead-metal',)),
    ('antimony', ('metal',)),
    ('argon', ('noble-gas',)),
    ('arsenic', ('chemical-element',)),
    ('astatine', ('chemical-element',)),
    ('atomic-mass', ('attribute',)),
    ('atomic-migration', ('event',)),
    ('atomism', ('concept',)),
    ('barium', ('metal',)),
    ('barium-dioxide', ('baryta',)),
    ('barium-hydroxide', ('baryta',)),
    ('barium-monoxide', ('baryta',)),
    ('baryta', ('substance',)),
    ('base-metal', ('metal',)),
    ('basic-iron', ('pig-iron',)),
    ('berkelium', ('metal',)),
    ('beryllium', ('metal',)),
    ('beta-iron', ('iron',)),
    ('bismuth', ('metal',)),
    ('blister-copper', ('copper',)),
    ('bohrium', ('chemical-element',)),
    ('bone-black', ('char',)),
    ('boron', ('chemical-element',)),
    ('bromine', ('nonmetal',)),
    ('buckminsterfullerene', ('fullerene',)),
    ('cadmium', ('metal',)),
    ('calcium', ('metal',)),
    ('calcium-ion', ('calcium',)),
    ('californium', ('metal',)),
    ('carbon-black', ('carbon', 'chemical')),
    ('carbon-nanotube', ('fullerene',)),
    ('carbonado', ('carbon', 'mineral')),
    ('cast-iron', ('iron',)),
    ('catalyst', ('substance',)),
    ('catalytic-activity', ('linear-dimension',)),
    ('cerium', ('metal',)),
    ('cesium', ('metal',)),
    ('cesium-137', ('cesium', 'radioactive-material', 'radioisotope')),
    ('char', ('carbon',)),
    ('charcoal', ('carbon', 'fuel')),
    ('chemical-activity', ('condition',)),
    ('chemical-association', ('chemical-process',)),
    ('chemical-bond', ('natural-event',)),
    ('chemical-buffer', ('compound',)),
    ('chemical-chain', ('chemical-group', 'concept')),
    ('chemical-decomposition', ('chemical-process', 'chemical-reaction')),
    ('chemical-dimorphism', ('attribute',)),
    ('chemical-dissociation', ('chemical-process',)),
    ('chemical-group', ('physical-object',)),
    ('chemical-indicator', ('material',)),
    ('chemical-phenomenon', ('natural-event',)),
    ('chemical-polymorphism', ('chemical-phenomenon',)),
    ('chemical-process', ('process',)),
    ('chemist', ('scientist',)),
    ('chlorine', ('chemical-element',)),
    ('chromium', ('metal',)),
    ('cinder-pig', ('pig-iron',)),
    ('closed-chain', ('chemical-chain',)),
    ('cobalt', ('metal',)),
    ('cobalt-60', ('cobalt',)),
    ('coin-silver', ('silver',)),
    ('curium', ('metal', 'radioactive-material')),
    ("dalton's-law", ('concept',)),
    ('darmstadtium', ('chemical-element',)),
    ('delta-iron', ('iron',)),
    ('displacement-reaction', ('chemical-process', 'chemical-reaction')),
    ('distillation-rectification', ('process',)),
    ('distribution-law', ('concept',)),
    ('dubnium', ('chemical-element',)),
    ('dysprosium', ('metal',)),
    ('einsteinium', ('metal',)),
    ('electrolysis', ('chemical-decomposition',)),
    ('electron-acceptor', ('compound',)),
    ('electronegativity', ('attribute',)),
    ('elemental-abundance', ('ratio',)),
    ('emulsion', ('mixture',)),
    ('equilibrium-constant', ('number',)),
    ('equilibrium-law', ('concept',)),
    ('erbium', ('metal',)),
    ('europium', ('metal',)),
    ('fermium', ('metal',)),
    ('fluorine', ('nonmetal',)),
    ('fluorocarbon', ('compound',)),
    ('francium', ('metal', 'radioactive-material')),
    ('fullerene', ('carbon',)),
    ('gadolinium', ('metal',)),
    ('gallium', ('metal',)),
    ('galvanized-iron', ('iron',)),
    ('gamma-iron', ('iron',)),
    ('germanium', ('chemical-element', 'material')),
    ('gold-dust', ('gold',)),
    ('graphite', ('carbon',)),
    ('green-gold', ('gold',)),
    ('grid-metal', ('antimonial-lead',)),
    ('guinea-gold', ('gold',)),
    ('hafnium', ('metal',)),
    ('hard-lead', ('lead-metal',)),
    ('hassium', ('chemical-element',)),
    ('heavy-metal', ('metal',)),
    ('helium', ('noble-gas', 'nonmetal')),
    ("henry's-law", ('concept',)),
    ('holmium', ('metal',)),
    ('hydrogen', ('chemical-element',)),
    ('imbibition', ('absorption',)),
    ('indium', ('metal',)),
    ('ingot-iron', ('iron',)),
    ('iodine', ('nonmetal',)),
    ('iodine-125', ('iodine',)),
    ('iodine-131', ('iodine', 'isotope')),
    ('ion', ('particle',)),
    ('iridium', ('metal',)),
    ('isotope', ('atom',)),
    ('krypton', ('noble-gas',)),
    ('lanthanum', ('metal',)),
    ('law-of-constant-proportion', ('concept',)),
    ('law-of-equivalent-proportions', ('concept',)),
    ('law-of-mass-action', ('concept',)),
    ('law-of-multiple-proportions', ('concept',)),
    ('lawrencium', ('chemical-element',)),
    ('liquid-nitrogen', ('liquid', 'nitrogen')),
    ('liquid-oxygen', ('liquid', 'oxygen')),
    ('lithium', ('metal',)),
    ('long-chain', ('chemical-chain',)),
    ('lutetium', ('metal',)),
    ('magnesium', ('metal',)),
    ('manganese', ('metal',)),
    ('meitnerium', ('chemical-element',)),
    ('mendelevium', ('chemical-element',)),
    ('mercury', ('metal',)),
    ('mine-pig', ('pig-iron',)),
    ('mixture', ('chemical',)),
    ('molecular-weight', ('attribute',)),
    ('molybdenum', ('metal',)),
    ('monovalent-atom', ('atom',)),
    ('neodymium', ('metal',)),
    ('neon', ('noble-gas',)),
    ('neptunium', ('metal', 'radioactive-material')),
    ('ni-hard', ('alloy-iron',)),
    ('ni-resist', ('alloy-iron',)),
    ('nickel', ('metal',)),
    ('niobium', ('metal',)),
    ('nitrogen', ('chemical-element',)),
    ('nobelium', ('chemical-element',)),
    ('noble-gas', ('chemical-element',)),
    ('noble-metal', ('metal',)),
    ('nonmetal', ('chemical-element',)),
    ('organic-chemistry', ('chemistry',)),
    ('osmium', ('metal',)),
    ('osmosis', ('process',)),
    ('palladium', ('metal',)),
    ('pencil-lead', ('graphite',)),
    ('periodic-law', ('concept',)),
    ('periodic-table', ('information',)),
    ('ph-value', ('concentration',)),
    ('phosphorus', ('chemical-element',)),
    ('pig-iron', ('alloy', 'iron')),
    ('pig-lead', ('lead-metal',)),
    ('platinum', ('noble-metal',)),
    ('plutonium', ('chemical-element', 'radioactive-material')),
    ('plutonium-239', ('plutonium', 'radioisotope')),
    ('polonium', ('metal', 'radioactive-material')),
    ('polymer', ('compound',)),
    ('polyvalence', ('state',)),
    ('pot-metal', ('alloy', 'cast-iron')),
    ('potassium', ('metal',)),
    ('praseodymium', ('metal',)),
    ('promethium', ('metal', 'radioactive-material')),
    ('protactinium', ('metal',)),
    ('radioactive-material', ('material',)),
    ('radiocarbon', ('carbon', 'radioactive-material', 'radioisotope')),
    ('radiochlorine', ('chlorine', 'radioactive-material', 'radioisotope')),
    ('radioisotope', ('isotope',)),
    ('radium', ('metal', 'radioactive-material')),
    ('radon', ('noble-gas', 'radioactive-material')),
    ('reverse-osmosis', ('osmosis',)),
    ('rhenium', ('metal',)),
    ('rhodium', ('metal',)),
    ('roentgenium', ('chemical-element',)),
    ('rubidium', ('metal',)),
    ('ruthenium', ('metal',)),
    ('rutherfordium', ('chemical-element',)),
    ('samarium', ('metal',)),
    ('saturation-point', ('condition',)),
    ('scandium', ('metal',)),
    ('scrap-iron', ('iron',)),
    ('seaborgium', ('chemical-element',)),
    ('selenium', ('chemical-element',)),
    ('sensitizer', ('substance',)),
    ('silicon', ('chemical-element', 'material')),
    ('spelter', ('zinc',)),
    ('spiegeleisen', ('pig-iron',)),
    ('state-of-matter', ('chemical-phenomenon',)),
    ('stoichiometry', ('ratio',)),
    ('strontium', ('metal',)),
    ('strontium-90', ('strontium',)),
    ('structural-iron', ('iron',)),
    ('sublimation', ('change',)),
    ('swedish-iron', ('wrought-iron',)),
    ('tantalum', ('metal',)),
    ('technetium', ('metal', 'radioactive-material')),
    ('tellurium', ('chemical-element',)),
    ('terbium', ('metal',)),
    ('thallium', ('metal',)),
    ('theory-of-dissociation', ('concept',)),
    ('theory-of-indicators', ('concept',)),
    ('thorium', ('metal', 'radioactive-material')),
    ('thorium-228', ('radioisotope', 'thorium')),
    ('thulium', ('metal',)),
    ('titanium', ('metal',)),
    ('trace-element', ('chemical-element',)),
    ('transactinide', ('chemical-element',)),
    ('transuranic-element', ('chemical-element',)),
    ('tritium', ('hydrogen', 'radioactive-material', 'radioisotope')),
    ('tungsten', ('metal',)),
    ('ununbium', ('chemical-element',)),
    ('ununhexium', ('chemical-element',)),
    ('ununpentium', ('chemical-element',)),
    ('ununquadium', ('chemical-element',)),
    ('ununtrium', ('chemical-element',)),
    ('uranium', ('metal', 'radioactive-material')),
    ('uranium-235', ('uranium',)),
    ('uranium-238', ('uranium',)),
    ('valence', ('attribute',)),
    ('vanadium', ('metal',)),
    ('weapons-plutonium', ('plutonium-239',)),
    ('wrought-iron', ('iron',)),
    ('xenon', ('noble-gas',)),
    ('ytterbium', ('metal',)),
    ('yttrium', ('metal',)),
    ('zinc', ('metal',)),
    ('zirconium', ('metal',)),
)
