"""The `geography` pack, version 4: 995 categories, adopted by merge.

GENERATED — do not edit by hand. Built by consensus in the sister repo
github.com/petfold/ontodag-core (packs/geography, commit 0db7b31) from WordNet 3.0
and Wikidata with hand rulings; every name is a plain word that no everyday
sense already owns (a pack never takes an everyday word). It presumes `core`,
which `pack geography` applies first; core's names appear below only as parents.
`BORROWED` are names that belong to a sibling pack — entered parentless so
this pack adopts on its own, filed the moment the sibling is adopted
(refinement by merge). ontodag-core's docs/UPPER.md §8 is the record.
"""

VERSION = 4

BORROWED = ('classification-scheme', 'data-processing', 'database', 'file-format', 'theory')

# (name, parents) — sorted by name.
PACK = (
    ('abyssal-plain', ('ocean-floor', 'plain')),
    ('abyssal-zone', ('ocean-floor', 'pelagic-zone')),
    ('achondrite', ('rock',)),
    ('adobe-clay', ('clay',)),
    ('advection', ('motion', 'process')),
    ('aegean-island', ('island',)),
    ('aeolian-deflation', ('geological-erosion',)),
    ('aerial-photography', ('photography',)),
    ('aerology', ('meteorology',)),
    ('aeronautical-chart', ('chart',)),
    ('africa', ('continent',)),
    ('afro-eurasia', ('landmass',)),
    ('afterglow', ('natural-event',)),
    ('aftershock', ('tremor',)),
    ('air-mass', ('atmosphere', 'atmospheric-state')),
    ('air-pocket', ('natural-event',)),
    ('airstream', ('wind',)),
    ('albers-projection', ('conic-projection',)),
    ('alluvial-fan', ('geological-formation',)),
    ('alluvial-flat', ('flatland',)),
    ('alluvial-sediment', ('sediment',)),
    ('alluvial-soil', ('soil',)),
    ('alp', ('mountain',)),
    ('alpine-glacier', ('glacier',)),
    ('alps', ('mountain-range',)),
    ('altitude', ('geographic-coordinate',)),
    ('altocumulus', ('cumulus',)),
    ('altostratus', ('stratus',)),
    ('amazon-river', ('river',)),
    ('americas', ('landmass',)),
    ('ammonite', ('fossil',)),
    ('andes', ('mountain-range',)),
    ('antarctic-circle', ('circle-of-latitude',)),
    ('antarctic-ice-sheet', ('ice-sheet',)),
    ('antarctica', ('continent',)),
    ('anticyclone', ('atmospheric-state',)),
    ('antipodes', ('geographic-point',)),
    ('antitrade-wind', ('prevailing-wind',)),
    ('antitrades', ('prevailing-wind',)),
    ('aquifer', ('geological-formation',)),
    ('archean', ('eon',)),
    ('archipelago', ('land', 'landform')),
    ('arctic-circle', ('circle-of-latitude',)),
    ('arctic-ocean', ('ocean',)),
    ('arete', ('ridge',)),
    ('argil', ('clay',)),
    ('arid-climate', ('climate',)),
    ('arroyo', ('gully',)),
    ('artificial-horizon', ('instrument',)),
    ('ascent', ('slope',)),
    ('asia', ('continent',)),
    ('asthenosphere', ('layer',)),
    ('astrolabe', ('instrument',)),
    ('atlantic-ocean', ('ocean',)),
    ('atlas', ('book',)),
    ('atmospheric-circulation', ('natural-event',)),
    ('atmospheric-electricity', ('natural-event',)),
    ('atmospheric-halo', ('natural-event',)),
    ('atmospheric-layer', ('earth-atmosphere',)),
    ('atmospheric-science', ('earth-science',)),
    ('atmospheric-state', ('weather',)),
    ('atoll', ('coral-reef', 'island')),
    ('aurora', ('natural-event',)),
    ('aurora-australis', ('aurora',)),
    ('aurora-borealis', ('aurora',)),
    ('australian-continent', ('continent',)),
    ('autumnal-equinox', ('equinox',)),
    ('avalanche', ('natural-event',)),
    ('axial-tilt', ('angle',)),
    ('azimuthal-equidistant-projection', ('azimuthal-projection',)),
    ('azimuthal-projection', ('map-projection',)),
    ('backwater', ('body-of-water',)),
    ('bad-weather', ('weather',)),
    ('barrier-island', ('island',)),
    ('barrier-reef', ('coral-reef',)),
    ('bathymetric-chart', ('chart', 'topographic-map')),
    ('bathymetry', ('activity', 'hydrography')),
    ('bayou', ('lake',)),
    ('beach-erosion', ('geological-erosion',)),
    ('beachfront', ('land',)),
    ('beaufort-scale', ('measure', 'scale')),
    ('bedrock', ('rock',)),
    ('beidou', ('global-navigation-satellite-system',)),
    ('belemnite', ('fossil',)),
    ('bentonite', ('clay',)),
    ('berm', ('ledge',)),
    ('bight', ('bay',)),
    ('billabong', ('stream',)),
    ('bioclimatology', ('climatology',)),
    ('biome', ('region',)),
    ('biosphere', ('earth-sphere',)),
    ('bise', ('north-wind',)),
    ('blizzard', ('storm',)),
    ('blue-jet', ('atmospheric-electricity',)),
    ('bluff', ('cliff', 'earth-bank')),
    ('bog', ('wetland',)),
    ('bog-soil', ('soil',)),
    ('boulder', ('rock',)),
    ('brook', ('stream',)),
    ('brooklet', ('brook',)),
    ('buoy', ('device',)),
    ('butte', ('hill', 'natural-elevation')),
    ('caldera', ('landform', 'natural-depression', 'volcanic-crater')),
    ('caliche', ('sedimentary-rock', 'soil')),
    ('calm-air', ('wind',)),
    ('cambrian', ('geological-period',)),
    ('canyon', ('ravine',)),
    ('canyonside', ('slope',)),
    ('cape', ('coast',)),
    ('carboniferous', ('geological-period',)),
    ('cardinal-compass-point', ('compass-point',)),
    ('caribbean-island', ('island',)),
    ('cartesian-coordinate-system', ('coordinate-system',)),
    ('cartogram', ('thematic-map',)),
    ('cartography', ('engineering', 'geography')),
    ('cascade', ('waterfall',)),
    ('cataract', ('waterfall',)),
    ('cavern', ('cave',)),
    ('cay', ('coral-reef',)),
    ('celestial-equator', ('great-circle', 'place')),
    ('celestial-horizon', ('place',)),
    ('celestial-navigation', ('navigation',)),
    ('cenozoic', ('geological-era',)),
    ('chernozemic-soil', ('loam',)),
    ('china-clay', ('clay',)),
    ('chinook', ('wind',)),
    ('chondrite', ('rock',)),
    ('choropleth-map', ('thematic-map',)),
    ('circle-of-latitude', ('circle', 'geographic-line')),
    ('cirque', ('natural-basin',)),
    ('cirrocumulus', ('cirrus',)),
    ('cirrostratus', ('cirrus',)),
    ('cirrus', ('cloud',)),
    ('clast', ('rock',)),
    ('clastic-rock', ('rock',)),
    ('clear-air-turbulence', ('turbulence',)),
    ('climate-classification', ('classification-scheme', 'concept')),
    ('climate-oscillation', ('natural-event',)),
    ('climatic-zone', ('geographical-area',)),
    ('climatology', ('atmospheric-science', 'meteorology', 'physical-geography')),
    ('cloud-bank', ('cloud',)),
    ('cloud-ceiling', ('altitude',)),
    ('cloudiness', ('bad-weather',)),
    ('clunch', ('soil',)),
    ('coal-seam', ('mineral-seam',)),
    ('coast', ('geographical-feature', 'land', 'shore')),
    ('coastal-piloting', ('navigation',)),
    ('coastal-plain', ('plain',)),
    ('coastline', ('place',)),
    ('cold-front', ('weather-front',)),
    ('cold-wave', ('weather',)),
    ('cold-weather', ('weather',)),
    ('compass', ('instrument',)),
    ('compass-card', ('magnetic-compass',)),
    ('compass-point', ('concept',)),
    ('compass-rose', ('symbol',)),
    ('condensation', ('natural-event',)),
    ('conformal-projection', ('map-projection',)),
    ('conic-projection', ('map-projection',)),
    ('continental-climate', ('climate',)),
    ('continental-drift', ('geological-phenomenon', 'geological-process')),
    ('continental-glacier', ('glacier',)),
    ('continental-shelf', ('landform', 'ocean-floor')),
    ('continental-slope', ('landform', 'ocean-floor')),
    ('contour-line', ('isoline',)),
    ('contour-map', ('map',)),
    ('contrail', ('cloud',)),
    ('convection', ('process',)),
    ('convergent-boundary', ('plate-boundary',)),
    ('coordinate-system', ('concept',)),
    ('coordinated-universal-time', ('time-standard',)),
    ('coral-reef', ('reef',)),
    ('coriolis-force', ('concept',)),
    ('crag', ('cliff',)),
    ('crater', ('natural-depression',)),
    ('cretaceous', ('geological-period',)),
    ('crosswind', ('wind',)),
    ('crustal-movement', ('event',)),
    ('cryosphere', ('earth-sphere',)),
    ('cumulonimbus', ('cloud',)),
    ('cumulus', ('cloud',)),
    ('cyclone', ('atmospheric-state', 'low')),
    ('cyclonic-storm', ('windstorm',)),
    ('cylindrical-projection', ('map-projection',)),
    ('dale', ('valley',)),
    ('daylight-saving-time', ('practice', 'time-standard')),
    ('dead-reckoning', ('navigation',)),
    ('dead-sea', ('lake',)),
    ('decimal-degrees', ('code',)),
    ('dell', ('hollow',)),
    ('depth-finder', ('instrument',)),
    ('desert-soil', ('soil',)),
    ('devonian', ('geological-period',)),
    ('dew', ('condensation',)),
    ('dew-point', ('quantity',)),
    ('diapir', ('geological-formation',)),
    ('differential-gps', ('global-positioning-system', 'gnss-augmentation')),
    ('digital-elevation-model', ('model',)),
    ('direct-tide', ('high-tide',)),
    ('distributary', ('stream',)),
    ('ditch', ('waterway',)),
    ('divergent-boundary', ('plate-boundary',)),
    ('doldrums', ('wind',)),
    ('downdraft', ('draught',)),
    ('downhill', ('declivity',)),
    ('downland', ('highland',)),
    ('downpour', ('rain',)),
    ('drainage-basin', ('geographical-area',)),
    ('drizzle', ('precipitation', 'rain')),
    ('drought', ('condition',)),
    ('dry-season', ('season',)),
    ('due-east', ('cardinal-compass-point',)),
    ('due-west', ('cardinal-compass-point',)),
    ('dune', ('hill', 'natural-ridge')),
    ('dust-devil', ('whirlwind',)),
    ('dust-storm', ('windstorm',)),
    ('earth-atmosphere', ('earth-sphere',)),
    ('earth-bank', ('natural-ridge',)),
    ('earth-centered-earth-fixed', ('geographic-coordinate-system', 'spatial-reference-system')),
    ('earth-crust', ('layer',)),
    ('earth-inner-core', ('layer',)),
    ('earth-magnetic-field', ('natural-event',)),
    ('earth-mantle', ('layer',)),
    ('earth-orbit', ('orbit',)),
    ('earth-outer-core', ('layer',)),
    ('earth-radius', ('quantity',)),
    ('earth-rotation', ('natural-event',)),
    ('earth-sphere', ('earth-structure', 'layer')),
    ('earth-structure', ('structure',)),
    ('east-by-north', ('compass-point',)),
    ('east-by-south', ('compass-point',)),
    ('east-northeast', ('compass-point',)),
    ('east-southeast', ('compass-point',)),
    ('east-wind', ('wind',)),
    ('eastern-hemisphere', ('hemisphere',)),
    ('ebbtide', ('tide',)),
    ('echo-sounding', ('sonar',)),
    ('ecliptic', ('place',)),
    ('economic-geography', ('geography',)),
    ('economic-geology', ('geology',)),
    ('ecoregion', ('region',)),
    ('eddy', ('event',)),
    ('el-nino', ('ocean-current',)),
    ('el-nino-southern-oscillation', ('climate-oscillation',)),
    ('elves-emission', ('atmospheric-electricity',)),
    ('endogeny', ('geological-phenomenon',)),
    ('endonym', ('place-name',)),
    ('eon', ('geological-time-division',)),
    ('epicenter', ('geographic-point',)),
    ('epoch', ('geological-time-division',)),
    ('epsg-geodetic-parameter-dataset', ('dataset',)),
    ('equal-area-projection', ('map-projection',)),
    ('equator', ('geographic-line',)),
    ('equatorial-current', ('ocean-current',)),
    ('equidistant-projection', ('map-projection',)),
    ('equinox', ('natural-event',)),
    ('equirectangular-projection', ('cylindrical-projection', 'equidistant-projection')),
    ('erosive-wash', ('streambed',)),
    ('escarpment', ('landform', 'slope')),
    ('esker', ('natural-ridge',)),
    ('estuary', ('body-of-water', 'river-mouth')),
    ('etrs89', ('geodetic-datum',)),
    ('eurasia', ('landmass',)),
    ('europe', ('continent',)),
    ('evaporite', ('sediment',)),
    ('exonym', ('place-name',)),
    ('exosphere', ('atmospheric-layer',)),
    ('fault-line', ('geographic-line',)),
    ('figure-of-the-earth', ('shape',)),
    ('fine-spray', ('precipitation',)),
    ('fire-pit', ('cavity',)),
    ('firestorm', ('flame', 'storm')),
    ('firth', ('estuary',)),
    ('fjord', ('bay', 'inlet')),
    ('flash-flood', ('flood',)),
    ('flatland', ('plain',)),
    ('flood-tide', ('tide',)),
    ('floodhead', ('flash-flood',)),
    ('floodplain', ('plain',)),
    ('flowage', ('body-of-water',)),
    ('flurry', ('snow',)),
    ('fohn', ('wind',)),
    ('folium', ('geological-formation',)),
    ('foothill', ('hill', 'natural-elevation')),
    ('ford', ('body-of-water',)),
    ('foreland', ('land',)),
    ('foreshock', ('tremor',)),
    ('foreshore', ('geological-formation',)),
    ('forked-lightning', ('lightning',)),
    ('freezing-rain', ('rain',)),
    ('freezing-weather', ('cold-weather',)),
    ('fresh-breeze', ('breeze',)),
    ('fresh-gale', ('gale',)),
    ('frigid-zone', ('climatic-zone',)),
    ('frost-heave', ('geological-phenomenon',)),
    ('fucoid', ('fossil',)),
    ("fuller's-earth", ('soil',)),
    ('gale', ('wind',)),
    ('galileo-navigation-system', ('global-navigation-satellite-system',)),
    ('gall-peters-projection', ('cylindrical-projection',)),
    ('gazetteer', ('dictionary',)),
    ('gentle-breeze', ('breeze',)),
    ('geochemistry', ('chemistry', 'geology')),
    ('geocode', ('code',)),
    ('geocoding', ('activity', 'data-processing')),
    ('geocoding-system', ('coordinate-system',)),
    ('geodesy', ('geophysics',)),
    ('geodetic-datum', ('spatial-reference-system',)),
    ('geodetic-network', ('collection',)),
    ('geographic-coordinate', ('quantity',)),
    ('geographic-coordinate-system', ('coordinate-system',)),
    ('geographic-data', ('information',)),
    ('geographic-data-format', ('file-format', 'information')),
    ('geographic-information-system', ('software',)),
    ('geographic-line', ('geographic-point',)),
    ('geographic-point', ('place',)),
    ('geographical-area', ('place',)),
    ('geographical-feature', ('natural-object', 'place')),
    ('geohash', ('geocode', 'geocoding', 'geocoding-system')),
    ('geoid', ('shape',)),
    ('geojson', ('geographic-data-format',)),
    ('geologic-time-scale', ('time-standard',)),
    ('geological-abrasion', ('geological-erosion',)),
    ('geological-cataclysm', ('geological-phenomenon',)),
    ('geological-eon', ('geological-time-division',)),
    ('geological-era', ('geological-time-division',)),
    ('geological-erosion', ('geological-process',)),
    ('geological-fault', ('crack', 'geological-formation')),
    ('geological-formation', ('physical-object',)),
    ('geological-heave', ('event',)),
    ('geological-horizon', ('layer',)),
    ('geological-period', ('geological-time-division',)),
    ('geological-phenomenon', ('natural-event',)),
    ('geological-process', ('process',)),
    ('geological-time-division', ('quantity',)),
    ('geological-trough', ('natural-depression',)),
    ('geology', ('earth-science',)),
    ('geomagnetic-pole', ('geographic-point',)),
    ('geomatics', ('engineering',)),
    ('geomorphology', ('geography', 'geophysics')),
    ('geonames', ('gazetteer',)),
    ('geophysics', ('geology', 'physics')),
    ('geopotential', ('quantity',)),
    ('geospatial-analysis', ('activity', 'data-processing')),
    ('geosphere', ('earth-sphere',)),
    ('geotagging', ('activity', 'data-processing')),
    ('geotiff', ('geographic-data-format',)),
    ('getty-thesaurus-of-geographic-names', ('gazetteer',)),
    ('geyser', ('hot-spring', 'landform')),
    ('gilgai-soil', ('soil',)),
    ('glacial-ablation', ('geological-erosion',)),
    ('glacial-boulder', ('boulder',)),
    ('glacial-period', ('geological-time-division',)),
    ('glacial-till', ('soil',)),
    ('glaciation', ('geological-process',)),
    ('glaciology', ('hydrology',)),
    ('glen', ('valley',)),
    ('global-navigation-satellite-system', ('satellite-navigation',)),
    ('global-positioning-system', ('global-navigation-satellite-system',)),
    ('glonass', ('global-navigation-satellite-system',)),
    ('gnomonic-projection', ('azimuthal-projection',)),
    ('gnss-augmentation', ('method',)),
    ('gobi-desert', ('desert',)),
    ('good-weather', ('weather',)),
    ('gorge', ('canyon',)),
    ('gps-exchange-format', ('geographic-data-format',)),
    ('gps-receiver', ('instrument',)),
    ('gps-time', ('time-standard',)),
    ('grassland', ('biome', 'geographical-area')),
    ('gravimetry', ('activity',)),
    ('gravity-anomaly', ('quantity',)),
    ('great-barrier-reef', ('coral-reef',)),
    ('great-circle', ('line',)),
    ('great-circle-distance', ('quantity',)),
    ('great-rift-valley', ('valley',)),
    ('greenhouse-effect', ('natural-event',)),
    ('greenland', ('island',)),
    ('greenland-ice-sheet', ('ice-sheet',)),
    ('gregorian-calendar', ('solar-calendar',)),
    ('grotto', ('cave',)),
    ('groundmass', ('rock-material',)),
    ('groundwater', ('water',)),
    ('growler', ('iceberg',)),
    ('gulch', ('gorge',)),
    ('gulf', ('bay',)),
    ('gulf-stream', ('ocean-current',)),
    ('gully', ('body-of-water', 'valley')),
    ('gust', ('wind',)),
    ('guyot', ('seamount',)),
    ('gyrocompass', ('instrument', 'tool')),
    ('hadean', ('eon',)),
    ('hadley-cell', ('atmospheric-circulation',)),
    ('hail', ('precipitation',)),
    ('hailstorm', ('storm',)),
    ('harmattan', ('trade-wind',)),
    ('haversine-formula', ('formula',)),
    ('headwind', ('wind',)),
    ('heat-wave', ('weather',)),
    ('height-above-mean-sea-level', ('altitude',)),
    ('high-pressure-area', ('air-mass',)),
    ('high-sea', ('body-of-water',)),
    ('high-tide', ('tide',)),
    ('high-wind', ('wind',)),
    ('highland', ('natural-elevation', 'place')),
    ('hillside', ('slope',)),
    ('himalayas', ('mountain-range',)),
    ('hogback', ('ridge',)),
    ('hollow', ('valley',)),
    ('holocene', ('epoch',)),
    ('homolosine-projection', ('equal-area-projection',)),
    ('hoodoo', ('geological-formation',)),
    ('horizontal-datum', ('geodetic-datum',)),
    ('horse-latitude', ('place',)),
    ('hot-spring', ('body-of-water', 'natural-spring')),
    ('hot-weather', ('weather',)),
    ('hour-circle', ('place',)),
    ('humidity', ('quantity',)),
    ('humus', ('soil',)),
    ('hurricane', ('cyclonic-storm', 'tropical-cyclone')),
    ('hydrography', ('geography', 'oceanography')),
    ('hydrology', ('geophysics',)),
    ('hydrosphere', ('earth-sphere',)),
    ('hypocenter', ('place',)),
    ('hypsography', ('geology',)),
    ('ice-age', ('geological-period',)),
    ('ice-cap', ('glacier', 'ice-mass')),
    ('ice-field', ('glacier', 'ice-mass')),
    ('ice-floe', ('ice', 'ice-mass')),
    ('ice-mass', ('geological-formation',)),
    ('ice-sheet', ('glacier',)),
    ('ice-shelf', ('glacier', 'ice-mass')),
    ('ice-storm', ('storm',)),
    ('iceberg', ('ice', 'ice-mass')),
    ('iers-reference-meridian', ('prime-meridian',)),
    ('igneous-intrusion', ('rock',)),
    ('igneous-rock', ('rock-material',)),
    ('igneous-sill', ('rock',)),
    ('inclinometer', ('instrument', 'tool')),
    ('index-fossil', ('fossil',)),
    ('indian-ocean', ('ocean',)),
    ('indurated-clay', ('soil',)),
    ('inertial-navigation-system', ('navigational-system',)),
    ('inlet', ('body-of-water', 'landform')),
    ('insolation', ('natural-event',)),
    ('instrument-flying', ('activity',)),
    ('intercardinal-direction', ('compass-point',)),
    ('interglacial', ('geological-time-division',)),
    ('international-atomic-time', ('time-standard',)),
    ('international-date-line', ('geographic-line',)),
    ('international-terrestrial-reference-system', ('spatial-reference-system',)),
    ('ionosphere', ('atmospheric-layer',)),
    ('isobar', ('isoline',)),
    ('isoline', ('line',)),
    ('isostasy', ('equilibrium',)),
    ('isotherm', ('isoline',)),
    ('isthmus', ('land', 'landform')),
    ('japan-current', ('ocean-current',)),
    ('jet-stream', ('airstream',)),
    ('julian-day', ('time-standard',)),
    ('jurassic', ('geological-period',)),
    ('karst', ('landform',)),
    ('katabatic-wind', ('wind',)),
    ('kettle-hole', ('natural-depression',)),
    ('keyhole-markup-language', ('geographic-data-format',)),
    ('khamsin', ('wind',)),
    ('kitty-litter', ('clay',)),
    ('knoll', ('hill',)),
    ('kopje', ('knoll',)),
    ('koppen-climate-classification', ('climate-classification',)),
    ('la-nina', ('climate-oscillation',)),
    ('lagoon', ('lake',)),
    ('lake-baikal', ('lake',)),
    ('lake-bed', ('waterbody-bed',)),
    ('lakefront', ('geological-formation',)),
    ('lakeside', ('shore',)),
    ('lambert-conformal-conic-projection', ('conic-projection',)),
    ('land-accretion', ('increase',)),
    ('land-neck', ('land',)),
    ('landfall', ('seashore', 'shore')),
    ('landmass', ('land',)),
    ('landslide', ('geological-phenomenon',)),
    ('landslip', ('descent',)),
    ('laterite', ('soil',)),
    ('latitude', ('angle', 'geographic-coordinate')),
    ('lava', ('magma',)),
    ('leaf-mold', ('soil',)),
    ('leap-second', ('time-standard',)),
    ('leap-year', ('quantity',)),
    ('ledge', ('natural-ridge',)),
    ('leeward-tide', ('tide',)),
    ('levanter', ('east-wind',)),
    ('levelling', ('surveying',)),
    ('lidar', ('instrument', 'remote-sensing')),
    ('light-air', ('breeze',)),
    ('light-breeze', ('breeze',)),
    ('lighthouse', ('building',)),
    ('lightning', ('atmospheric-electricity',)),
    ('liman', ('lagoon',)),
    ('limnology', ('earth-science',)),
    ('line-squall', ('squall',)),
    ('line-storm', ('rainstorm',)),
    ('lithosphere', ('layer',)),
    ('littoral', ('seashore', 'shore')),
    ('llano', ('plain',)),
    ('loam', ('soil',)),
    ('local-mean-time', ('solar-time',)),
    ('location-based-service', ('software',)),
    ('loch', ('lake',)),
    ('lode', ('mineral-vein',)),
    ('loess', ('sediment', 'soil')),
    ('longitude', ('angle', 'geographic-coordinate')),
    ('low-tide', ('tide',)),
    ('lowland', ('natural-depression', 'plain')),
    ('lunar-calendar', ('calendar',)),
    ('lunar-crater', ('crater',)),
    ('lunisolar-calendar', ('calendar',)),
    ('maar', ('volcanic-crater',)),
    ('magma', ('fluid', 'rock-material')),
    ('magnetic-compass', ('compass',)),
    ('magnetic-declination', ('angle',)),
    ('magnetic-meridian', ('meridian',)),
    ('magnetosphere', ('region',)),
    ('mainland', ('land',)),
    ('map-legend', ('document',)),
    ('map-projection', ('method',)),
    ('map-scale', ('ratio',)),
    ("mare's-tail", ('cirrus',)),
    ('mariana-trench', ('oceanic-trench',)),
    ('marine-chronometer', ('instrument',)),
    ('marine-transgression', ('geological-phenomenon',)),
    ('marl', ('soil',)),
    ('massif', ('geological-formation', 'landform')),
    ('meander', ('curved-shape', 'geographical-feature')),
    ('mercalli-scale', ('measure',)),
    ('mercator-projection', ('cylindrical-projection',)),
    ('meridian', ('great-circle', 'place')),
    ('mesa', ('plateau',)),
    ('mesosphere', ('atmospheric-layer',)),
    ('mesozoic', ('geological-era',)),
    ('metamorphic-rock', ('rock-material',)),
    ('meteor-shower', ('natural-event',)),
    ('microfossil', ('fossil',)),
    ('micropaleontology', ('paleontology',)),
    ('mid-ocean-ridge', ('oceanic-ridge',)),
    ('mid-water', ('body-of-water',)),
    ('midnight-sun', ('natural-event',)),
    ('military-grid-reference-system', ('spatial-reference-system',)),
    ('mineral-seam', ('layer',)),
    ('mineral-vein', ('geological-formation',)),
    ('mineralogy', ('geology',)),
    ('mining-geology', ('economic-geology',)),
    ('mistral', ('north-wind',)),
    ('moderate-breeze', ('breeze',)),
    ('moderate-gale', ('gale',)),
    ('mohorovicic-discontinuity', ('earth-structure',)),
    ('mollweide-projection', ('equal-area-projection',)),
    ('moment-magnitude-scale', ('measure', 'scale')),
    ('monocline', ('geological-formation',)),
    ('monsoon', ('wind',)),
    ('monsoon-season', ('rainy-season',)),
    ('monsoon-wind', ('wind',)),
    ('moor', ('habitat', 'plain')),
    ('mother-lode', ('lode',)),
    ('mount-everest', ('mountain',)),
    ('mountainside', ('slope',)),
    ('nacreous-cloud', ('cloud',)),
    ('narrows', ('strait',)),
    ('national-mapping-agency', ('organization',)),
    ('natural-basin', ('natural-depression',)),
    ('natural-elevation', ('geological-formation',)),
    ('natural-ridge', ('natural-elevation',)),
    ('natural-spring', ('geographical-feature', 'geological-formation')),
    ('nautical-chart', ('chart',)),
    ('naval-chart', ('chart',)),
    ('navigation', ('activity', 'skill')),
    ('navigational-bearing', ('angle',)),
    ('navigational-system', ('device',)),
    ('neap-tide', ('tide',)),
    ('nebule', ('cloud',)),
    ('neogene', ('geological-period',)),
    ('nephology', ('meteorology',)),
    ('neritic-zone', ('geographical-area', 'pelagic-zone')),
    ('nile', ('river',)),
    ('nimbostratus', ('cloud',)),
    ('nimbus', ('cloud',)),
    ("noah's-flood", ('flood',)),
    ('north', ('cardinal-compass-point',)),
    ('north-america', ('continent',)),
    ('north-american-datum', ('geodetic-datum',)),
    ('north-by-east', ('compass-point',)),
    ('north-by-west', ('compass-point',)),
    ('north-equatorial-current', ('equatorial-current',)),
    ('north-northeast', ('compass-point',)),
    ('north-northwest', ('compass-point',)),
    ('north-pole', ('geographic-pole',)),
    ('north-wind', ('wind',)),
    ('northeast', ('compass-point',)),
    ('northeast-by-east', ('compass-point',)),
    ('northeast-by-north', ('compass-point',)),
    ('northeaster', ('storm',)),
    ('northern-hemisphere', ('hemisphere',)),
    ('northwest', ('compass-point',)),
    ('northwest-by-north', ('compass-point',)),
    ('northwest-by-west', ('compass-point',)),
    ('northwest-wind', ('wind',)),
    ('oasis', ('geographical-area', 'geographical-feature')),
    ('oblate-spheroid', ('shape',)),
    ("observer's-meridian", ('meridian',)),
    ('occluded-front', ('weather-front',)),
    ('ocean-current', ('motion',)),
    ('ocean-floor', ('geological-formation', 'waterbody-bed')),
    ('ocean-gyre', ('ocean-current',)),
    ('ocean-swell', ('wave',)),
    ('oceanfront', ('geological-formation',)),
    ('oceania', ('geographical-area',)),
    ('oceanic-ridge', ('geological-formation', 'landform')),
    ('oceanic-trench', ('landform', 'natural-depression')),
    ('oceanography', ('earth-science',)),
    ('odometer', ('instrument',)),
    ('offing', ('body-of-water',)),
    ('omnirange', ('artifact',)),
    ('open-location-code', ('geocode',)),
    ('ordovician', ('geological-period',)),
    ('ore-bed', ('rock-bed',)),
    ('orogeny', ('geological-process',)),
    ('orology', ('geology',)),
    ('orthographic-projection', ('azimuthal-projection',)),
    ('orthometric-height', ('altitude',)),
    ('orthophoto', ('image',)),
    ('outcrop', ('rock',)),
    ('outthrust', ('outcrop',)),
    ('overlying-stratum', ('layer',)),
    ('oxbow', ('land',)),
    ('oxbow-lake', ('lake',)),
    ('ozone-layer', ('atmospheric-layer',)),
    ('pacific-ocean', ('ocean',)),
    ('paleoanthropology', ('vertebrate-paleontology',)),
    ('paleobiology', ('biology', 'paleontology')),
    ('paleobotany', ('paleobiology',)),
    ('paleodendrology', ('paleobotany',)),
    ('paleogene', ('geological-period',)),
    ('paleogeology', ('geology',)),
    ('paleomammalogy', ('paleozoology',)),
    ('paleontology', ('earth-science',)),
    ('paleornithology', ('paleozoology',)),
    ('paleozoic', ('geological-era',)),
    ('paleozoology', ('paleobiology',)),
    ('pebble', ('rock',)),
    ('pedology', ('earth-science',)),
    ('pedometer', ('instrument', 'tool')),
    ('pedosphere', ('earth-sphere',)),
    ('pelagic-zone', ('body-of-water',)),
    ('peneplain', ('plain',)),
    ('peninsula', ('land', 'landform')),
    ('permafrost', ('physical-object',)),
    ('permian', ('geological-period',)),
    ('peruvian-current', ('ocean-current',)),
    ('petrifaction', ('rock',)),
    ('petroleum-geology', ('economic-geology',)),
    ('petrology', ('geology',)),
    ('phanerozoic', ('eon',)),
    ('photogrammetry', ('remote-sensing',)),
    ('physical-geography', ('geography',)),
    ('piedmont', ('slope',)),
    ('piedmont-glacier', ('glacier',)),
    ('place-name', ('name',)),
    ('placer', ('alluvial-sediment',)),
    ('plain', ('land', 'landform')),
    ('planation', ('geological-erosion',)),
    ('planet-earth', ('planet',)),
    ('plat-map', ('map',)),
    ('plate-boundary', ('geological-formation',)),
    ('plate-tectonics', ('concept', 'theory')),
    ('plateau', ('highland', 'landform')),
    ('pleistocene', ('epoch',)),
    ('podzol', ('soil',)),
    ('point-of-interest', ('geographic-point',)),
    ('polar-circle', ('place',)),
    ('polar-climate', ('climate',)),
    ('polar-glacier', ('continental-glacier',)),
    ('polar-vortex', ('cyclone',)),
    ('polyconic-projection', ('conic-projection',)),
    ('polynya', ('body-of-water',)),
    ('pond', ('lake', 'landform')),
    ('postal-address', ('information',)),
    ('postal-code', ('code',)),
    ('pothole', ('natural-depression',)),
    ('prairie', ('grassland',)),
    ('prairie-soil', ('soil',)),
    ('precipice', ('cliff',)),
    ('precipitation', ('weather',)),
    ('prevailing-westerly', ('west-wind',)),
    ('prevailing-wind', ('wind',)),
    ('prime-meridian', ('meridian',)),
    ('principle-of-superposition', ('scientific-principle',)),
    ('promontory', ('landform', 'natural-elevation')),
    ('proterozoic', ('eon',)),
    ('quaternary', ('geological-period',)),
    ('quicksand', ('cavity',)),
    ('radar', ('instrument', 'tool')),
    ('rain-wash', ('washout',)),
    ('rainstorm', ('rain', 'storm')),
    ('rainy-season', ('season',)),
    ('rapids', ('stream', 'waterway')),
    ('ravine', ('valley',)),
    ('real-time-kinematic-positioning', ('gnss-augmentation',)),
    ('red-clay', ('clay', 'mineral')),
    ('reef', ('shoal',)),
    ('reference-ellipsoid', ('shape',)),
    ('regosol', ('soil',)),
    ('regur', ('loam',)),
    ('relict', ('geological-formation',)),
    ('relief-map', ('topographic-map',)),
    ('remote-sensing', ('activity',)),
    ('residual-soil', ('soil',)),
    ('reverse-geocoding', ('geocoding',)),
    ('rhumb-line', ('line',)),
    ('richter-magnitude-scale', ('measure', 'scale')),
    ('rift-valley', ('valley',)),
    ('rill', ('water-channel',)),
    ('rip-current', ('ocean-current',)),
    ('riparian-forest', ('forest',)),
    ('ripple-mark', ('natural-ridge',)),
    ('river-boulder', ('boulder',)),
    ('river-delta', ('alluvial-sediment', 'plain', 'river-mouth')),
    ('river-mouth', ('geographic-point', 'geological-formation')),
    ('river-source', ('geographic-point', 'stream')),
    ('riverbank', ('bank', 'landform', 'shore')),
    ('riverbed', ('waterbody-bed',)),
    ('rivulet', ('stream',)),
    ('road-map', ('map',)),
    ('robinson-projection', ('map-projection',)),
    ('rock-bed', ('layer',)),
    ('rock-cycle', ('geological-process',)),
    ('rock-foliation', ('geological-process',)),
    ('rock-material', ('material',)),
    ('rock-matrix', ('rock-material',)),
    ('rock-wall', ('geological-formation',)),
    ('sahara', ('desert',)),
    ('salt-flat', ('flatland',)),
    ('salt-lick', ('sediment',)),
    ('saltpan', ('natural-basin',)),
    ('sand-spit', ('cape',)),
    ('sandbank', ('earth-bank',)),
    ('sandbar', ('shoal',)),
    ('sandblast', ('gust',)),
    ('santa-ana', ('wind',)),
    ('satellite-geodesy', ('geodesy',)),
    ('satellite-imagery', ('image',)),
    ('satellite-navigation', ('navigational-system',)),
    ('savanna', ('grassland',)),
    ('scablands', ('physical-object',)),
    ('scale-bar', ('symbol',)),
    ('sea-breeze', ('breeze',)),
    ('sea-cove', ('inlet',)),
    ('sea-ice', ('ice-mass',)),
    ('sea-level', ('quantity', 'vertical-datum')),
    ('sea-sound', ('inlet',)),
    ('seamount', ('mountain', 'natural-elevation')),
    ('seaquake', ('earthquake',)),
    ('seaside', ('seashore',)),
    ('season', ('event',)),
    ('sediment-saltation', ('process',)),
    ('sedimentary-clay', ('soil',)),
    ('sedimentary-rock', ('rock-material',)),
    ('sedimentation', ('geological-phenomenon', 'geological-process')),
    ('seiche', ('wave',)),
    ('seif-dune', ('dune',)),
    ('seismic-disturbance', ('earthquake',)),
    ('seismic-wave', ('wave',)),
    ('seismology', ('geophysics',)),
    ('seismometer', ('instrument',)),
    ('sextant', ('instrument',)),
    ('shallows', ('body-of-water',)),
    ('shapefile', ('geographic-data-format',)),
    ('shingling', ('rock-material',)),
    ('shoal', ('landform', 'sandbank')),
    ('shore', ('geological-formation',)),
    ('shore-boulder', ('boulder',)),
    ('sidereal-day', ('quantity',)),
    ('sidereal-time', ('time-standard',)),
    ('silt', ('sediment', 'soil')),
    ('silurian', ('geological-period',)),
    ('simoom', ('wind',)),
    ('sinkhole', ('natural-depression',)),
    ('sinusoidal-projection', ('equal-area-projection',)),
    ('sketch-map', ('map',)),
    ('ski-slope', ('slope',)),
    ('slack-water', ('tide',)),
    ('sleet', ('precipitation',)),
    ('snowfield', ('plain',)),
    ('soil-erosion', ('geological-erosion',)),
    ('soil-horizon', ('layer',)),
    ('solar-calendar', ('calendar',)),
    ('solar-halo', ('atmospheric-halo',)),
    ('solar-time', ('time-standard',)),
    ('solstice', ('natural-event',)),
    ('sonar', ('instrument',)),
    ('sonic-depth-finder', ('depth-finder',)),
    ('south', ('cardinal-compass-point',)),
    ('south-america', ('continent',)),
    ('south-by-east', ('compass-point',)),
    ('south-by-west', ('compass-point',)),
    ('south-equatorial-current', ('equatorial-current',)),
    ('south-pole', ('geographic-pole',)),
    ('south-sea-islands', ('island',)),
    ('south-southeast', ('compass-point',)),
    ('south-southwest', ('compass-point',)),
    ('south-wind', ('wind',)),
    ('southeast', ('compass-point',)),
    ('southeast-by-east', ('compass-point',)),
    ('southeast-by-south', ('compass-point',)),
    ('southeaster', ('wind',)),
    ('southern-hemisphere', ('hemisphere',)),
    ('southern-ocean', ('ocean',)),
    ('southwest', ('compass-point',)),
    ('southwest-by-south', ('compass-point',)),
    ('southwest-by-west', ('compass-point',)),
    ('southwester', ('wind',)),
    ('spatial-database', ('database', 'information')),
    ('spatial-reference-system', ('coordinate-system',)),
    ('speleology', ('geology',)),
    ('spherical-coordinate-system', ('coordinate-system',)),
    ('spring-tide', ('high-tide',)),
    ('sprite-lightning', ('atmospheric-electricity',)),
    ('squall', ('wind',)),
    ('squall-line', ('cold-front',)),
    ('star-chart', ('map',)),
    ('steppe', ('grassland', 'plain')),
    ('stereographic-projection', ('azimuthal-projection',)),
    ('storm-cloud', ('cloud',)),
    ('storm-surge', ('flood',)),
    ('strait', ('landform', 'water-channel')),
    ('stratigraphic-superposition', ('accretion',)),
    ('stratigraphy', ('geology',)),
    ('stratosphere', ('atmospheric-layer',)),
    ('stratum', ('layer',)),
    ('stratus', ('cloud',)),
    ('streambed', ('waterbody-bed',)),
    ('strong-breeze', ('breeze',)),
    ('strong-gale', ('gale',)),
    ('subcontinent', ('landmass',)),
    ('subduction', ('geological-process',)),
    ('subsoil', ('soil',)),
    ('subtropics', ('climatic-zone',)),
    ('summer-solstice', ('solstice',)),
    ('sunset', ('natural-event',)),
    ('supercontinent', ('continent', 'landmass')),
    ('supertwister', ('tornado',)),
    ('survey-benchmark', ('geographic-point', 'geographical-feature')),
    ('surveying', ('activity',)),
    ('swale', ('geological-trough',)),
    ('swamp', ('wetland',)),
    ('taiga', ('biome', 'habitat')),
    ('tailwind', ('wind',)),
    ('talus', ('geological-formation', 'gravel')),
    ('tar-pit', ('cavity', 'landform')),
    ('tarn', ('lake',)),
    ('tectonic-plate', ('geographical-feature', 'geological-formation')),
    ('tectonics', ('geology',)),
    ('temperate-climate', ('climate',)),
    ('temperate-zone', ('climatic-zone',)),
    ('temperature-inversion', ('natural-event',)),
    ('terrace', ('plateau',)),
    ('terrain', ('geographical-feature',)),
    ('terrestrial-globe', ('map', 'model')),
    ('territorial-waters', ('body-of-water',)),
    ('thaw', ('weather',)),
    ('thematic-map', ('map',)),
    ('thermal-updraft', ('convection', 'wind')),
    ('thermohaline-circulation', ('ocean-current',)),
    ('thermosphere', ('atmospheric-layer',)),
    ('thunder', ('sound',)),
    ('thunderhead', ('cumulus',)),
    ('thundershower', ('rainstorm',)),
    ('thunderstorm', ('storm', 'weather')),
    ('tidal-basin', ('natural-basin',)),
    ('tidal-bore', ('tidal-flow', 'wave')),
    ('tidal-flow', ('event',)),
    ('tidal-range', ('quantity',)),
    ('tidal-river', ('stream',)),
    ('tide-gauge', ('instrument',)),
    ('tide-table', ('document',)),
    ('tideland', ('seashore', 'shore')),
    ('tidewater', ('coastal-plain',)),
    ('tideway', ('water-channel',)),
    ('time-standard', ('concept',)),
    ('time-zone', ('geographical-area',)),
    ('topographic-map', ('map',)),
    ('topography', ('physical-geography',)),
    ('toponymy', ('field-of-study',)),
    ('topsoil', ('soil',)),
    ('tor-hill', ('hill', 'outcrop')),
    ('tor-rock', ('rock',)),
    ('tornado', ('cyclonic-storm', 'whirlwind')),
    ('torrent', ('event',)),
    ('total-station', ('instrument', 'tool')),
    ('trade-wind', ('prevailing-wind',)),
    ('tramontane', ('north-wind',)),
    ('transform-fault', ('geological-fault', 'plate-boundary')),
    ('transit-zone', ('geographical-area',)),
    ('transverse-mercator-projection', ('cylindrical-projection',)),
    ('travel-distance', ('quantity',)),
    ('travel-route', ('path',)),
    ('tremor', ('earthquake',)),
    ('triangulation', ('surveying',)),
    ('triassic', ('geological-period',)),
    ('tributary', ('stream',)),
    ('trilateration', ('method',)),
    ('tropic', ('circle-of-latitude',)),
    ('tropic-of-cancer', ('circle-of-latitude',)),
    ('tropic-of-capricorn', ('circle-of-latitude',)),
    ('tropical-climate', ('climate',)),
    ('tropical-cyclone', ('cyclone',)),
    ('tropical-rainforest', ('biome',)),
    ('tropical-year', ('quantity',)),
    ('tropics', ('climatic-zone',)),
    ('troposphere', ('atmospheric-layer',)),
    ('tsunami', ('calamity', 'wave')),
    ('tundra', ('biome', 'plain')),
    ('tundra-soil', ('soil',)),
    ('turbulence', ('bad-weather',)),
    ('turn-by-turn-navigation', ('navigation',)),
    ('twilight-zone', ('pelagic-zone',)),
    ('typhoon', ('cyclonic-storm', 'tropical-cyclone')),
    ('underlying-stratum', ('layer',)),
    ('undertide', ('event',)),
    ('undertow', ('ocean-current', 'undertide')),
    ('unix-time', ('time-standard',)),
    ('updraft', ('draught',)),
    ('upheaval', ('event',)),
    ('uphill', ('ascent',)),
    ('upwelling', ('ocean-current',)),
    ('utm-coordinate-system', ('spatial-reference-system',)),
    ('veld', ('grassland',)),
    ('vernal-equinox', ('equinox',)),
    ('vertebrate-paleontology', ('paleozoology',)),
    ('vertical-circle', ('place',)),
    ('vertical-datum', ('geodetic-datum',)),
    ('vincenty-formulae', ('formula',)),
    ('virga', ('precipitation',)),
    ('visual-range', ('attribute',)),
    ('volcanic-crater', ('geological-formation', 'place')),
    ('volcanic-eruption', ('event',)),
    ('volcanism', ('geological-phenomenon',)),
    ('volcanology', ('geophysics',)),
    ('wadi', ('gully',)),
    ('wall-rock', ('rock',)),
    ('warm-front', ('weather-front',)),
    ('washout', ('soil-erosion',)),
    ('water-cycle', ('natural-event',)),
    ('water-hole', ('pond',)),
    ('water-table', ('geological-formation', 'surface')),
    ('waterbody-bed', ('natural-depression',)),
    ('watercourse', ('water-channel',)),
    ('watershed', ('geographical-feature',)),
    ('waterside', ('land',)),
    ('waterspout', ('tornado',)),
    ('waterway', ('body-of-water',)),
    ('wave-height', ('quantity',)),
    ('waypoint', ('geographic-point',)),
    ('weather-balloon', ('aircraft', 'balloon')),
    ('weather-forecast', ('prognosis',)),
    ('weather-forecasting', ('information',)),
    ('weather-map', ('map',)),
    ('weather-radar', ('radar',)),
    ('weather-satellite', ('satellite',)),
    ('weather-station', ('facility',)),
    ('weathering', ('geological-process',)),
    ('web-map', ('map',)),
    ('web-mercator-projection', ('mercator-projection',)),
    ('well-known-text', ('geographic-data-format',)),
    ('west-by-north', ('compass-point',)),
    ('west-by-south', ('compass-point',)),
    ('west-northwest', ('compass-point',)),
    ('west-southwest', ('compass-point',)),
    ('west-wind', ('wind',)),
    ('westerlies', ('prevailing-wind',)),
    ('western-hemisphere', ('hemisphere',)),
    ('wetland', ('geographical-feature', 'habitat', 'land')),
    ('wgs-84', ('world-geodetic-system',)),
    ('whinstone', ('rock',)),
    ('whirlpool', ('event',)),
    ('whirlwind', ('wind', 'windstorm')),
    ('whiteout', ('weather',)),
    ('whole-gale', ('gale',)),
    ('wide-area-augmentation-system', ('gnss-augmentation',)),
    ('wiesenboden', ('soil',)),
    ('wind-rose', ('artifact', 'weather-map')),
    ('windstorm', ('storm',)),
    ('winkel-tripel-projection', ('map-projection',)),
    ('winter-solstice', ('solstice',)),
    ('world-geodetic-system', ('geodetic-datum',)),
    ('wormcast', ('fossil',)),
    ('xenolith', ('rock',)),
    ('classification-scheme', ()),
    ('data-processing', ()),
    ('database', ()),
    ('file-format', ()),
    ('theory', ()),
)
