"""The `space` pack, version 2: 352 categories, adopted by merge.

GENERATED — do not edit by hand. Built by consensus in the sister repo
github.com/petfold/ontodag-core (packs/space, commit fb54269) from WordNet 3.0
and Wikidata with hand rulings; every name is a plain word that no everyday
sense already owns (a pack never takes an everyday word). It presumes `core`,
which `pack space` applies first; core's names appear below only as parents.
`BORROWED` are names that belong to a sibling pack — entered parentless so
this pack adopts on its own, filed the moment the sibling is adopted
(refinement by merge). ontodag-core's docs/UPPER.md §8 is the record.
"""

VERSION = 2

BORROWED = ('coordinate-system',)

# (name, parents) — sorted by name.
PACK = (
    ('absolute-magnitude', ('quantity',)),
    ('active-galactic-nucleus', ('celestial-body',)),
    ('adaptive-optics', ('method',)),
    ('aerolite', ('meteorite',)),
    ('aerospace-engineering', ('engineering',)),
    ('age-of-the-universe', ('quantity',)),
    ('amateur-astronomy', ('activity', 'astronomy')),
    ('andromeda-galaxy', ('spiral-galaxy',)),
    ('annular-eclipse', ('solar-eclipse',)),
    ('aphelion', ('apoapsis',)),
    ('apoapsis', ('apsis', 'place')),
    ('apogee', ('apoapsis',)),
    ('apojove', ('apoapsis',)),
    ('apollo-11', ('space-mission',)),
    ('apollo-program', ('space-program',)),
    ('aposelene', ('apoapsis',)),
    ('apparent-magnitude', ('quantity',)),
    ('apsis', ('orbital-position',)),
    ('armillary-sphere', ('map', 'model')),
    ('ascending-node', ('orbital-node',)),
    ('asterism', ('concept',)),
    ('asteroid', ('minor-planet',)),
    ('asteroid-belt', ('circumstellar-disc',)),
    ('astrobiology', ('astronomy', 'biology')),
    ('astrometry', ('astronomy',)),
    ('astronaut', ('person',)),
    ('astronautics', ('engineering',)),
    ('astronomical-catalog', ('document',)),
    ('astronomical-conjunction', ('encounter',)),
    ('astronomical-nutation', ('natural-event',)),
    ('astronomical-opposition', ('natural-event',)),
    ('astronomical-photometry', ('activity',)),
    ('astronomical-telescope', ('telescope',)),
    ('astronomical-transit', ('natural-event',)),
    ('astronomy-satellite', ('device', 'satellite')),
    ('astrophotography', ('photography',)),
    ('astrophysics', ('astronomy',)),
    ('atmospheric-entry', ('event',)),
    ('autumnal-equinoctial-point', ('equinoctial-point',)),
    ('autumnal-equinox', ('equinox',)),
    ('axial-precession', ('natural-event',)),
    ('barred-spiral-galaxy', ('spiral-galaxy',)),
    ('barycenter', ('point',)),
    ('bayer-designation', ('code',)),
    ('big-bang', ('explosion',)),
    ('binary-star', ('star-system',)),
    ('black-hole', ('stellar-remnant',)),
    ('bolide', ('meteor',)),
    ('booster-rocket', ('engine',)),
    ('brown-dwarf', ('celestial-body',)),
    ('callisto', ('galilean-satellite',)),
    ('cassegrainian-telescope', ('reflecting-telescope',)),
    ('celestial-coordinate-system', ('concept', 'coordinate-system')),
    ('celestial-culmination', ('place',)),
    ('celestial-equator', ('place',)),
    ('celestial-mechanics', ('astronomy',)),
    ('celestial-navigation', ('activity',)),
    ('celestial-point', ('point',)),
    ('celestial-pole', ('celestial-point', 'place')),
    ('celestial-sphere', ('surface',)),
    ('ceres', ('asteroid', 'dwarf-planet')),
    ('charon', ('natural-satellite',)),
    ('chiron', ('asteroid',)),
    ('chromosphere', ('layer',)),
    ('circumstellar-disc', ('celestial-body',)),
    ('cnsa', ('space-agency',)),
    ('collimator', ('instrument',)),
    ('communications-satellite', ('satellite', 'spacecraft')),
    ('coronal-mass-ejection', ('natural-event',)),
    ('cosmic-inflation', ('concept',)),
    ('cosmic-microwave-background', ('radiation',)),
    ('cosmic-ray', ('radiation',)),
    ('cosmological-constant', ('quantity',)),
    ('cosmologist', ('scientist',)),
    ('cosmology', ('astrophysics',)),
    ('coude-telescope', ('reflecting-telescope',)),
    ('crewed-spacecraft', ('spacecraft',)),
    ('cubesat', ('satellite',)),
    ('dark-energy', ('concept',)),
    ('dark-matter', ('substance',)),
    ('dark-nebula', ('nebula',)),
    ('declination', ('angle',)),
    ('deimos', ('natural-satellite',)),
    ('descending-node', ('orbital-node',)),
    ('diffuse-nebula', ('nebula',)),
    ('dwarf-galaxy', ('galaxy',)),
    ('dwarf-planet', ('celestial-body',)),
    ('earth-observation-satellite', ('satellite',)),
    ('eclipse', ('natural-event',)),
    ('ecliptic', ('place',)),
    ('ecliptic-coordinate-system', ('celestial-coordinate-system',)),
    ('elliptical-galaxy', ('galaxy',)),
    ('emission-nebula', ('nebula',)),
    ('enceladus', ('natural-satellite',)),
    ('ephemeris', ('document',)),
    ('equatorial-coordinate-system', ('celestial-coordinate-system',)),
    ('equatorial-telescope', ('instrument',)),
    ('equinoctial-point', ('place',)),
    ('equinox', ('natural-event',)),
    ('eris', ('dwarf-planet',)),
    ('escape-velocity', ('quantity',)),
    ('europa', ('galilean-satellite',)),
    ('european-space-agency', ('space-agency',)),
    ('event-horizon', ('region',)),
    ('exoplanet', ('planet',)),
    ('expansion-of-the-universe', ('natural-event',)),
    ('extravehicular-activity', ('activity',)),
    ('falcon-9', ('reusable-launch-system',)),
    ('field-glass', ('refracting-telescope',)),
    ('first-quarter', ('half-moon',)),
    ('fixed-star', ('star',)),
    ('flare-star', ('red-dwarf',)),
    ('full-moon', ('lunar-phase',)),
    ('galactic-coordinate-system', ('celestial-coordinate-system',)),
    ('galaxy-cluster', ('celestial-body', 'collection')),
    ('galaxy-group', ('collection',)),
    ('galaxy-supercluster', ('collection',)),
    ('galilean-satellite', ('natural-satellite',)),
    ('galilean-telescope', ('refracting-telescope',)),
    ('ganymede', ('galilean-satellite',)),
    ('gas-giant', ('planet',)),
    ('geomagnetic-storm', ('natural-event',)),
    ('geostationary-orbit', ('geosynchronous-orbit',)),
    ('geosynchronous-orbit', ('orbit',)),
    ('giant-star', ('star',)),
    ('globular-cluster', ('star-cluster',)),
    ('gravitational-lens', ('natural-event',)),
    ('gravitational-wave', ('wave',)),
    ('gravity-assist', ('method',)),
    ('half-moon', ('lunar-phase',)),
    ('harvest-moon', ('full-moon',)),
    ('heliocentric-orbit', ('orbit',)),
    ('heliosphere', ('region',)),
    ('herschelian-telescope', ('reflecting-telescope',)),
    ('hertzsprung-russell-diagram', ('image',)),
    ('hill-sphere', ('region',)),
    ('hohmann-transfer-orbit', ('orbit',)),
    ('horizontal-coordinate-system', ('celestial-coordinate-system',)),
    ('host-star', ('star',)),
    ('hour-angle', ('angle',)),
    ('hubble-space-telescope', ('space-telescope',)),
    ('hubbles-law', ('concept',)),
    ('human-spaceflight', ('spaceflight',)),
    ('ice-giant', ('planet',)),
    ('inferior-planet', ('major-planet',)),
    ('inner-planet', ('terrestrial-planet',)),
    ('interferometry', ('method',)),
    ('intergalactic-space', ('place',)),
    ('international-astronomical-union', ('organization',)),
    ('international-space-station', ('space-station',)),
    ('interplanetary-medium', ('substance',)),
    ('interstellar-medium', ('substance',)),
    ('interstellar-space', ('place',)),
    ('io', ('galilean-satellite',)),
    ('irregular-galaxy', ('galaxy',)),
    ('isro', ('space-agency',)),
    ('j2000', ('concept',)),
    ('james-webb-space-telescope', ('space-telescope',)),
    ('jovian-planet', ('major-planet',)),
    ('jupiter', ('planet',)),
    ('keplers-laws', ('concept',)),
    ('kessler-syndrome', ('concept',)),
    ('kuiper-belt', ('circumstellar-disc',)),
    ('kuiper-belt-object', ('minor-planet',)),
    ('lagrange-point', ('celestial-point',)),
    ('lambda-cdm-model', ('concept',)),
    ('lander', ('spacecraft',)),
    ('laniakea-supercluster', ('galaxy-supercluster',)),
    ('large-magellanic-cloud', ('dwarf-galaxy', 'irregular-galaxy')),
    ('last-quarter', ('half-moon',)),
    ('launch-pad', ('facility',)),
    ('launch-vehicle', ('rocket',)),
    ('light-pollution', ('condition',)),
    ('liquid-propellant-rocket', ('rocket',)),
    ('local-group', ('galaxy-group',)),
    ('low-earth-orbit', ('orbit',)),
    ('lunar-eclipse', ('eclipse',)),
    ('lunar-excursion-module', ('spacecraft',)),
    ('lunar-phase', ('appearance',)),
    ('magellanic-clouds', ('collection',)),
    ('magnetar', ('neutron-star',)),
    ('main-sequence', ('concept',)),
    ('maksutov-telescope', ('reflecting-telescope',)),
    ('mars', ('planet',)),
    ('medium-earth-orbit', ('orbit',)),
    ('mercury-planet', ('planet',)),
    ('messier-object', ('celestial-body',)),
    ('meteor', ('natural-event',)),
    ('meteor-shower', ('natural-event',)),
    ('meteor-swarm', ('collection',)),
    ('meteorite', ('meteoroid',)),
    ('meteoroid', ('celestial-body',)),
    ('micrometeorite', ('meteorite',)),
    ('milky-way', ('galaxy',)),
    ('minor-planet', ('celestial-body',)),
    ('multiple-star', ('star-system',)),
    ('nadir', ('place',)),
    ('nasa', ('space-agency',)),
    ('natural-satellite', ('celestial-body',)),
    ('navigation-satellite', ('satellite', 'spacecraft')),
    ('near-earth-object', ('celestial-body',)),
    ('nebula', ('celestial-body',)),
    ('neptune', ('planet',)),
    ('neutron-star', ('star', 'stellar-remnant')),
    ('new-general-catalogue', ('astronomical-catalog',)),
    ('new-moon', ('lunar-phase',)),
    ('newtonian-telescope', ('reflecting-telescope',)),
    ('nova', ('variable-star',)),
    ('nucleosynthesis', ('natural-event',)),
    ('observable-universe', ('region',)),
    ('observational-astronomy', ('astronomy',)),
    ('observatory', ('building',)),
    ('occultation', ('natural-event',)),
    ('oort-cloud', ('celestial-body',)),
    ('open-cluster', ('star-cluster',)),
    ('optical-telescope', ('astronomical-telescope',)),
    ('orbital-eccentricity', ('quantity',)),
    ('orbital-elements', ('quantity',)),
    ('orbital-inclination', ('quantity',)),
    ('orbital-mechanics', ('celestial-mechanics',)),
    ('orbital-node', ('place',)),
    ('orbital-period', ('quantity',)),
    ('orbital-position', ('celestial-point',)),
    ('orbital-spaceflight', ('spaceflight',)),
    ('orbiter', ('satellite',)),
    ('orion', ('constellation',)),
    ('outer-planet', ('major-planet',)),
    ('pallasite', ('meteorite',)),
    ('parallax', ('angle',)),
    ('partial-eclipse', ('event',)),
    ('periapsis', ('apsis', 'place')),
    ('perigee', ('periapsis',)),
    ('perihelion', ('periapsis',)),
    ('perijove', ('periapsis',)),
    ('periselene', ('periapsis',)),
    ('phobos', ('natural-satellite',)),
    ('photosphere', ('layer',)),
    ('planetarium', ('building',)),
    ('planetary-moon', ('natural-satellite',)),
    ('planetary-nebula', ('emission-nebula',)),
    ('planetary-rover', ('spacecraft',)),
    ('planetary-science', ('astronomy',)),
    ('planetary-system', ('celestial-body', 'collection')),
    ('planetesimal', ('celestial-body',)),
    ('pluto', ('dwarf-planet',)),
    ('polar-orbit', ('orbit',)),
    ('primary-body', ('celestial-body',)),
    ('proper-motion', ('quantity',)),
    ('protostar', ('star',)),
    ('pulsar', ('neutron-star',)),
    ('quasar', ('active-galactic-nucleus',)),
    ('radio-astronomy', ('observational-astronomy',)),
    ('radio-interferometer', ('radio-telescope',)),
    ('radio-telescope', ('astronomical-telescope',)),
    ('reconnaissance-satellite', ('earth-observation-satellite',)),
    ('red-dwarf', ('star',)),
    ('red-giant', ('giant-star',)),
    ('red-shift', ('natural-event',)),
    ('reflecting-telescope', ('optical-telescope',)),
    ('refracting-telescope', ('optical-telescope',)),
    ('reusable-launch-system', ('launch-vehicle', 'spacecraft')),
    ('right-ascension', ('angle',)),
    ('roche-limit', ('quantity',)),
    ('rocket-engine', ('engine',)),
    ('rocket-launch', ('event',)),
    ('sample-return-mission', ('space-mission',)),
    ('saturn', ('planet',)),
    ('saturn-v', ('launch-vehicle',)),
    ('scattered-disc', ('circumstellar-disc',)),
    ('schmidt-telescope', ('reflecting-telescope',)),
    ('selenology', ('astronomy',)),
    ('semi-major-axis', ('quantity',)),
    ('sidereal-day', ('quantity', 'sidereal-time')),
    ('sidereal-hour', ('quantity', 'sidereal-time')),
    ('sidereal-month', ('quantity', 'sidereal-time')),
    ('sidereal-time', ('concept',)),
    ('sidereal-year', ('quantity', 'sidereal-time')),
    ('siderite', ('meteorite',)),
    ('small-magellanic-cloud', ('dwarf-galaxy', 'irregular-galaxy')),
    ('solar-antapex', ('place',)),
    ('solar-apex', ('place',)),
    ('solar-cycle', ('natural-event',)),
    ('solar-eclipse', ('eclipse',)),
    ('solar-flare', ('natural-event',)),
    ('solar-physics', ('astronomy', 'physics')),
    ('solar-radiation', ('radiation',)),
    ('solar-system', ('planetary-system',)),
    ('solar-telescope', ('telescope',)),
    ('solar-wind', ('natural-event',)),
    ('solid-propellant-rocket', ('rocket',)),
    ('solstice', ('natural-event',)),
    ('soyuz-spacecraft', ('crewed-spacecraft', 'space-capsule')),
    ('space-agency', ('organization',)),
    ('space-capsule', ('spacecraft',)),
    ('space-debris', ('physical-object',)),
    ('space-mission', ('activity',)),
    ('space-probe', ('vehicle', 'weapon')),
    ('space-program', ('method',)),
    ('space-rendezvous', ('event',)),
    ('space-shuttle', ('reusable-launch-system',)),
    ('space-station', ('crewed-spacecraft', 'satellite')),
    ('space-suit', ('clothing',)),
    ('space-telescope', ('satellite', 'telescope')),
    ('space-weather', ('astrophysics',)),
    ('spaceflight', ('voyage',)),
    ('spaceport', ('facility',)),
    ('spacex', ('company',)),
    ('spectral-class', ('stellar-classification',)),
    ('spectrograph', ('instrument',)),
    ('spectroscopy', ('activity',)),
    ('spiral-galaxy', ('galaxy',)),
    ('sputnik-1', ('satellite',)),
    ('star-catalogue', ('astronomical-catalog',)),
    ('star-chart', ('data-chart',)),
    ('star-cluster', ('celestial-body', 'collection')),
    ('star-system', ('celestial-body', 'collection')),
    ('stellar-classification', ('concept',)),
    ('stellar-evolution', ('natural-event',)),
    ('stellar-parallax', ('parallax',)),
    ('stellar-remnant', ('celestial-body',)),
    ('suborbital-spaceflight', ('spaceflight',)),
    ('summer-solstice', ('solstice',)),
    ('sun-synchronous-orbit', ('polar-orbit',)),
    ('sunspot', ('natural-event',)),
    ('supergiant-star', ('star',)),
    ('superior-planet', ('major-planet',)),
    ('supermassive-black-hole', ('black-hole',)),
    ('supernova', ('star',)),
    ('supernova-remnant', ('emission-nebula',)),
    ('synodic-month', ('quantity',)),
    ('telescope', ('instrument',)),
    ('terrestrial-planet', ('planet',)),
    ('tidal-locking', ('natural-event',)),
    ('titan', ('natural-satellite',)),
    ('total-eclipse', ('event',)),
    ('trans-neptunian-object', ('minor-planet',)),
    ('transit-instrument', ('telescope',)),
    ('trapezium-cluster', ('multiple-star',)),
    ('triton', ('natural-satellite',)),
    ('uranus', ('planet',)),
    ('variable-star', ('star',)),
    ('venus', ('planet',)),
    ('vernal-equinoctial-point', ('equinoctial-point',)),
    ('vernal-equinox', ('equinox',)),
    ('virgo-supercluster', ('galaxy-supercluster',)),
    ('voyager-1', ('space-probe',)),
    ('voyager-2', ('space-probe',)),
    ('weather-satellite', ('earth-observation-satellite',)),
    ('white-dwarf', ('star', 'stellar-remnant')),
    ('winter-solstice', ('solstice',)),
    ('zenith', ('place',)),
    ('zodiac', ('place',)),
    ('coordinate-system', ()),
)
